/**
 * SoftMuteService — notification-only mute (kind:30078 / NIP-78, NIP-44 encrypted).
 *
 * "Soft mute" suppresses ONLY notifications generated by a user's interactions
 * with your notes (replies, reactions, zaps, reposts). Their posts still appear
 * in your timeline, replies, search, DMs. Their PV stays fully readable.
 *
 * Distinct from the full Mute list (`src/lists/mutes.ts`):
 *   - Full mute filters everywhere (feed, replies, threads, DMs, notifications)
 *     and replaces the PV with a "Muted" placeholder.
 *   - Soft mute is orthogonal: only NotificationsOrchestrator consumes it.
 *
 * Local cache in PerAccountLocalStorage for fast synchronous reads from the
 * notifications filter. Relay persistence via NIP-78 (kind:30078), NIP-44
 * self-encrypted (the list of "who annoys me" leaks relationships → sensitive).
 * d-tag: "noornote:soft-mutes".
 *
 * @service SoftMuteService
 * @purpose Cross-device-synced preference for suppressing notifications
 */

import { AuthService } from './AuthService';
import { NostrTransport } from './transport/NostrTransport';
import { OutboundRelaysOrchestrator } from './orchestration/OutboundRelaysOrchestrator';
import { PerAccountLocalStorage, StorageKeys } from './PerAccountLocalStorage';
import { ToastService } from './ToastService';
import { TypedEventBus } from '../core/TypedEventBus';
import { diagLog } from './DiagnosticLogger';

const NIP78_KIND = 30078;
const D_TAG = 'noornote:soft-mutes';
const PUBLISH_DEBOUNCE_MS = 1500;

export interface SoftMuteEntry {
  addedAt: number;
}

type SoftMuteMap = Record<string, SoftMuteEntry>;

export class SoftMuteService {
  private static instance: SoftMuteService | null = null;
  private auth: AuthService;
  private transport: NostrTransport;
  private pals: PerAccountLocalStorage;
  private eventBus: TypedEventBus;

  /** In-memory cache mirror of the PerAccountLocalStorage map for O(1) lookups. */
  private cache: Map<string, SoftMuteEntry> = new Map();

  /** Debounce timer for batching rapid toggles into one relay publish. */
  private publishTimer: ReturnType<typeof setTimeout> | null = null;

  private constructor() {
    this.auth = AuthService.getInstance();
    this.transport = NostrTransport.getInstance();
    this.pals = PerAccountLocalStorage.getInstance();
    this.eventBus = TypedEventBus.getInstance();
    this.loadCacheFromStorage();

    // On account switch / logout, drop the in-memory cache so the next
    // getInstance() for a different account starts fresh. The new account's
    // data is reloaded either by the next mutating call (loadCacheFromStorage
    // on construction already covered the initial load) or by syncFromRelays.
    this.eventBus.on('user:logout', () => {
      if (this.publishTimer) {
        clearTimeout(this.publishTimer);
        this.publishTimer = null;
      }
      this.cache.clear();
    });
    this.eventBus.on('user:login', () => {
      this.loadCacheFromStorage();
    });
  }

  public static getInstance(): SoftMuteService {
    if (!SoftMuteService.instance) {
      SoftMuteService.instance = new SoftMuteService();
    }
    return SoftMuteService.instance;
  }

  public destroy(): void {
    if (this.publishTimer) {
      clearTimeout(this.publishTimer);
      this.publishTimer = null;
    }
    this.cache.clear();
    SoftMuteService.instance = null;
  }

  // ── Reads ────────────────────────────────────────────────────

  public isSoftMuted(pubkey: string): boolean {
    return this.cache.has(pubkey);
  }

  public getAll(): SoftMuteMap {
    const out: SoftMuteMap = {};
    for (const [k, v] of this.cache) out[k] = v;
    return out;
  }

  // ── Mutations ────────────────────────────────────────────────

  public softMute(pubkey: string): void {
    if (!pubkey) return;
    if (this.cache.has(pubkey)) return;
    const user = this.auth.getCurrentUser();
    // Block self-soft-mute — never suppress your own notifications.
    if (user && user.pubkey === pubkey) return;

    this.cache.set(pubkey, { addedAt: Date.now() });
    this.persistLocal();
    this.eventBus.emit('soft-mute:updated');
    this.schedulePublish();
  }

  public unsoftMute(pubkey: string): void {
    if (!pubkey) return;
    if (!this.cache.delete(pubkey)) return;
    this.persistLocal();
    this.eventBus.emit('soft-mute:updated');
    this.schedulePublish();
  }

  public toggleSoftMute(pubkey: string): void {
    if (this.isSoftMuted(pubkey)) {
      this.unsoftMute(pubkey);
    } else {
      this.softMute(pubkey);
    }
  }

  // ── Storage ──────────────────────────────────────────────────

  private loadCacheFromStorage(): void {
    const map = this.pals.get<SoftMuteMap>(StorageKeys.SOFT_MUTED_PUBKEYS, {});
    this.cache.clear();
    if (map && typeof map === 'object') {
      for (const [k, v] of Object.entries(map)) {
        if (typeof v === 'object' && v !== null && typeof v.addedAt === 'number') {
          this.cache.set(k, v);
        }
      }
    }
  }

  private persistLocal(): void {
    this.pals.set(StorageKeys.SOFT_MUTED_PUBKEYS, this.getAll());
  }

  // ── Relay sync ──────────────────────────────────────────────

  /**
   * Fetch soft-mutes from relays and populate local cache.
   * Called on login / account switch.
   *
   * Merge strategy: relay value wins on first sync; thereafter the local
   * cache is canonical (it gets pushed on every change). If both sides have
   * diverged, we accept the union keyed by addedAt (relay entries that are
   * missing locally get added back; local-only entries stay and get pushed
   * on the next change).
   */
  public async syncFromRelays(): Promise<void> {
    const user = this.auth.getCurrentUser();
    if (!user) return;

    try {
      const relays = await OutboundRelaysOrchestrator.getInstance().getCombinedRelays([user.pubkey], true);
      if (relays.length === 0) return;

      const events = await this.transport.fetch(relays, [{
        kinds: [NIP78_KIND as number],
        authors: [user.pubkey],
        '#d': [D_TAG],
        limit: 1,
      }], 5000, false, 'SoftMuteSvc');

      if (events.length === 0) return;

      const event = events.sort((a, b) => b.created_at - a.created_at)[0];
      if (!event?.content) return;

      const plaintext = await this.auth.nip44Decrypt(event.content, user.pubkey);
      const remote = JSON.parse(plaintext);
      if (typeof remote !== 'object' || remote === null) return;

      let changed = false;
      for (const [pubkey, entry] of Object.entries(remote)) {
        if (this.cache.has(pubkey)) continue;
        if (typeof entry === 'object' && entry !== null && typeof (entry as SoftMuteEntry).addedAt === 'number') {
          this.cache.set(pubkey, entry as SoftMuteEntry);
          changed = true;
        }
      }
      if (changed) {
        this.persistLocal();
        this.eventBus.emit('soft-mute:updated');
      }
      diagLog('system', 'SoftMuteService synced from relays', { count: this.cache.size });
    } catch (error) {
      diagLog('system', 'SoftMuteService sync failed', { error: String(error) });
    }
  }

  private schedulePublish(): void {
    if (this.publishTimer) clearTimeout(this.publishTimer);
    this.publishTimer = setTimeout(() => {
      this.publishTimer = null;
      this.publishToRelays(this.getAll()).catch(() => {
        // Soft-fail: local state is already correct; sync will retry on next change.
      });
    }, PUBLISH_DEBOUNCE_MS);
  }

  private async publishToRelays(map: SoftMuteMap): Promise<void> {
    const user = this.auth.getCurrentUser();
    if (!user) return;

    try {
      const plaintext = JSON.stringify(map);
      const encrypted = await this.auth.nip44Encrypt(plaintext, user.pubkey);

      const unsigned = {
        kind: NIP78_KIND,
        created_at: Math.floor(Date.now() / 1000),
        tags: [['d', D_TAG]],
        content: encrypted,
        pubkey: user.pubkey,
      };

      const signed = await this.auth.signEvent(unsigned);
      if (!signed) {
        ToastService.show('Signing failed', 'error');
        return;
      }

      await this.transport.publishContent(signed);
      diagLog('system', 'SoftMuteService published to relays', { count: Object.keys(map).length });
    } catch (error) {
      diagLog('system', 'SoftMuteService publish failed', { error: String(error) });
      ToastService.show('Failed to sync soft mute', 'error');
    }
  }
}
